### PR TITLE
RA-1592 : Boostrap as a foundation for Reference Application UI Project. 

### PR DESCRIPTION
**Pull request by Akayeshmantha**
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now

1.Registration page icon-ok width issue fix.

This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592

### CODE REVIEW

**Comment by ssmusoke** [comment]
@Akayeshmantha can you share screenshots of the before and after

**Comment by Akayeshmantha** [comment]
Before 
b857feb584828734fe1c3e39dc427da55ff1ff16

**Comment by Akayeshmantha** [comment]
After

Screenshot from 2019-09-17 07-20-20

**Comment by Akayeshmantha** [comment]
@ssmusoke

**Pull request merged**
