### PR TITLE
RA-1811: 'toString()' should never be called on a String object

### PR DESCRIPTION
**Pull request by kdaud**
Ticket Id: https://issues.openmrs.org/browse/RA-1811

### CODE REVIEW

**Review by HerbertYiga — APPROVED** [review]
cc @sacull

**Comment by dkayiwa** [comment]
@sacull what do you think of this? 😊

**Comment by sacull** [comment]
@dkayiwa Sorry, but I didn't have access to Github for a month.

**Review by sacull — APPROVED** [review]

**Comment by dkayiwa** [comment]
@sacull oh sorry about that! Good to see you back. 😊

**Pull request merged**
