### PR TITLE
RA-1629: Adding ability to specify gender options in reg. app definition.

### PR DESCRIPTION
**Pull request by Ruhanga**
Ticket : https://issues.openmrs.org/browse/RA-1629

### CODE REVIEW

**Comment by solemabrothers** [comment]
@Ruhanga have you tested this, if so can you please add screenshots to the ticket. I tried testing it but it doesnt give me the ability to specify gender

**Comment by Ruhanga** [comment]
Hi @solemabrothers, I've attached an image to this effect. I also attached a link in the ticket description to the hastbin page containing an example reg app definition with `genderOptions` parameter configured.

**Comment by solemabrothers** [comment]
@Ruhanga i see you have this PR indicated as a Draft, does this mean its not yet ready for review

**Comment by solemabrothers** [comment]
Also the file https://hastebin.com/udajejiral.json, where do you expect to include it, I mean in which module

**Comment by Ruhanga** [comment]
Okay, @solemabrothers this can be reviewed. The config @ https://hastebin.com/udajejiral.json can be added to the Ref App. For example with demo's case @  https://demo.openmrs.org/openmrs/referenceapplication/manageApps.page . Remember to use the config Id as the app Id when saving the app definition.

**Comment by solemabrothers** [comment]
> 
> 
> Okay, @solemabrothers this can be reviewed. The config @ https://hastebin.com/udajejiral.json can be added to the Ref App. For example with demo's case @ https://demo.openmrs.org/openmrs/referenceapplication/manageApps.page . Remember to use the config Id as the app Id when saving the app definition.

So then why not include in registration app so that we don't have to make the configuration, my opinion is that it is better if its not a separate configuration but also part of registration app, that way whoever needs this functionality doesn't need to do the configs

**Comment by Ruhanga** [comment]
@solemabrothers, adding other gender options for registration apart from Male and Female, is not a primary use-case for many users of the Ref App. This is why the solution to resolve gender options is such that the registration app's gender options are configurable - not so hard to do in a few clicks.

**Comment by solemabrothers** [comment]
Okay that is noted

**Pull request merged**
