### PR TITLE
RA-1847: Fails silently when creating/editing relationships with non-Person names

### PR DESCRIPTION
**Pull request by tendomart**
Still failing to pick $$state object values picked from the rest call done when the user enters a name .
Anyone has an idea 
@mks-d  @mogoodrich

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@tendomart  what is the ticket Id for this?

**Comment by tendomart** [comment]
The response payload from the Rest call looks like this https://pastebin.com/npNn9BSw , but  i cannot reference or pick any values form the returned $$state (Json Object)

Tried to look around but all examples were of not great value.

**Comment by tendomart** [comment]
@HerbertYiga  it's at https://issues.openmrs.org/browse/RA-1847 , have you encountered such ?

**Comment by HerbertYiga** [comment]
> it's at https://issues.openmrs.org/browse/RA-1847 , have you encountered such ?

do you have steps to reproduce this ??

**Comment by brandones** [comment]
This doesn't do anything and is stale. Closing.

**Pull request closed without merging**
