### PR TITLE
Fix finger

### PR DESCRIPTION
**Pull request by jeandaboul**
adding two hidden input for mational biometric ID and local biometric ID

### CODE REVIEW

**Comment by HerbertYiga** [comment]
thanks @jeandaboul  this branch has conflicts that you can first resolve!!

**Comment by mseaton** [comment]
@jeandaboul - this is going to be very challenging to merge in.  There appear to be quite large-scale changes that are relatively specific to a particular implementation / use case, with m2sys fingerprint support built-in, and quite large modifications to the pom, ignored unit tests, and other changes specific to iSante+ that were perfectly fine in a fork that was purpose built for that implementation but which will need changes to be merged into the mainline branch.

Currently there are existing hooks in the registrationcore and registrationapp modules that have been provided to enable extension modules to plug in custom solutions.  For example, implementations currently support fingerprinting and connectivity to an MPI via adherence to certain conventions and hooking in with custom modules.  This may be an approach we need to explore here.

@dkayiwa interested in your thoughts as well.

**Comment by dkayiwa** [comment]
> interested in your thoughts as well.

@mseaton i completely agree with you!

**Comment by jeandaboul** [comment]
I am sorry @mseaton  @dkayiwa and @HerbertYiga  it was an issue with my local repository the push should be done to anther organization but i miss the configuration.

**Pull request closed without merging**
