### PR TITLE
RA-1584: All subsections to be configurable to combine as one subsection within their section

### PR DESCRIPTION
**Pull request by Ruhanga**
Ticket : https://issues.openmrs.org/browse/RA-1584

### CODE REVIEW

**Comment by dkayiwa** [comment]
@Ruhanga are you still doing anything on this?

**Comment by Ruhanga** [comment]
Yes @dkayiwa, I'm awaiting a review from @mogoodrich with a little more changes if needed.

**Comment by dkayiwa** [comment]
Did you notice that the pr has merge conflicts?

**Comment by Ruhanga** [comment]
Thank you @dkayiwa . I think this was because there were several commits here. I have squashed them into one. There are no merge conflicts now.

**Pull request merged**
