### PR TITLE
RA-1592: Boostrap as a foundation for the Reference Application UI.

### PR DESCRIPTION
**Pull request by Akayeshmantha**
This PR contains changes for the GSoC Project Bootstrap as a foundation for Ref App UI project.
It contains the following changes up to now

1.Registration page icon-ok width issue fix.
2. Demographic ui page fix.

This PR will have more commit's when the project is going forward.
Ticket ID :- https://issues.openmrs.org/browse/RA-1592

### CODE REVIEW

**Comment by Akayeshmantha** [comment]
@Ruhanga  done

**Comment by Ruhanga** [comment]
Hi @ssmusoke, could you approve and merge these changes? Thank you.

**Comment by dkayiwa** [comment]
git checkout -b Akayeshmantha-RA-1592 master

git pull https://github.com/Akayeshmantha/openmrs-module-registrationapp.git RA-1592

**Comment by Akayeshmantha** [comment]
@dkayiwa  what do u mean ?

**Comment by dkayiwa** [comment]
Sorry those were instructions for @ jwnasambu to test these changes locally.

**Comment by jwnasambu** [comment]
@dkayiwa have followed the above instructions. What next?

**Comment by Akayeshmantha** [comment]
HI @jwnasambu  

I think you have to check for the Demographic ui issue as @mks-d  mentioned in this thread

https://talk.openmrs.org/t/core-apps-patient-page-look-and-feel-different-on-desktop-browsers/24578/76?u=ayesh

**Comment by Akayeshmantha** [comment]
@ssmusoke  @dkayiwa  @Ruhanga  shall we merge this

**Comment by dkayiwa** [comment]
@jwnasambu it has been merged and hence you can test it from https://qa-refapp.openmrs.org

**Pull request merged**
