### PR TITLE
Added 'Relationship' section on patient registration page to allow addition of person relationships

### PR DESCRIPTION
**Pull request by themoonraker13**
Person Relationship in Patient Registration : https://talk.openmrs.org/t/relationships-in-reference-application/8988

@ssmusoke, please review the implementation and provide necessary feedback.

### CODE REVIEW

**Comment by dkayiwa** [comment]
@themoonraker13 thanks for working on this? Do you mind pointing me to the ticket for this change? If one does not exist, feel free to create it. :)

**Comment by ssmusoke** [comment]
@themoonraker13 have you seen the failed tests on travis?

**Comment by themoonraker13** [comment]
@ssmusoke must have missed something in hurry. Let me check and get back to you.

**Comment by ssmusoke** [comment]
@themoonraker13 okay, also create a ticket so that the PR can be reviewed properly

**Comment by themoonraker13** [comment]
@ssmusoke A ticket as in on https://issues.openmrs.org?? OR a GitHub issue??

**Pull request closed without merging**
