### PR TITLE
Integrating MPI Functionality

### PR DESCRIPTION
**Pull request by shaoyuancc**
Hi All,

This merge is meant to bring in MPI functionality primarily developed by SolDevlo for iSantePlus back into the master branch. 

Much of the discussion is recorded here: https://talk.openmrs.org/t/integration-with-openempi/11535/45

Jira Ticket: https://issues.openmrs.org/browse/RC-30

The commit is far from perfect, but it should not break anything and we have tested basic functionality such as registering a patient, updating a patient and importing a patient.

### CODE REVIEW

**Comment by shaoyuancc** [comment]
No that is registrationcore and this is registrationapp. but both are regarding the MPI functionality

**Comment by dkayiwa** [comment]
@shaoyuancc do you think this is ready for merging?

**Comment by dkayiwa** [comment]
@shaoyuancc just in case you did not see the above. 😊

**Comment by dkayiwa** [comment]
@shaoyuancc do you think we should merge this for now and do a follow up pull request if more changes are needed? Or would you rather we leave it?

**Comment by shaoyuancc** [comment]
Hi @dkayiwa i think that sounds good, it was definitely good to go to merge at the end of july!

**Comment by brandones** [comment]
Closing as stale.

**Pull request closed without merging**
