### PR TITLE
RA-982:Support Coded Person Attributes in Reference Application Registration

### PR DESCRIPTION
**Pull request by HerbertYiga**
for this ticket,https://issues.openmrs.org/browse/RA-982, i have made a conceptFragmentController that renders the available concept answers to the conceptFragment basing on a foreign key.As i come up with the conceptFragment i will be glad to hear from @wluyima @mogoodrich  @mseaton  about this since initially i was totally off of what was needed in my pr.

### CODE REVIEW

**Comment by HerbertYiga** [comment]
@wluyima  needed to here from you on this!

**Comment by dkayiwa** [comment]
@HerbertYiga on the JIRA ticket, can you add some screenshots to prove that this is working as expected?

**Comment by solemabrothers** [comment]
@dkayiwa @wluyima @HerbertYiga  any progress on this PR we need its usage in UgandaEMR??

**Comment by dkayiwa** [comment]
@solemabrothers have you reviewed it?

**Comment by solemabrothers** [comment]
Not yet, I wanted to know the status of the PR and then start from there

**Comment by dkayiwa** [comment]
Any pull request that you come across is waiting for review. 😊

**Comment by solemabrothers** [comment]
Ok then i will review

**Comment by solemabrothers** [comment]
@dkayiwa please make me a contributor to this project so that I can effectively review this PR. Thank you

**Comment by dkayiwa** [comment]
@solemabrothers you do not need any special permission to review pull requests. Is there anything  you are not able to do?

**Comment by solemabrothers** [comment]
I cant pull it for now

**Comment by dkayiwa** [comment]
What do you mean by that?

**Comment by solemabrothers** [comment]
I mean can't pull the PR to my local environment for testing

**Comment by dkayiwa** [comment]
@solemabrothers do the following:

git checkout -b HerbertYiga-RA-982 master
git pull https://github.com/HerbertYiga/openmrs-module-registrationapp.git RA-982

**Comment by solemabrothers** [comment]
ok thank you

**Comment by solemabrothers** [comment]
> @HerbertYiga on the JIRA ticket, can you add some screenshots to prove that this is working as expected?

@HerbertYiga did you respond to this, if so please help me with a link on where i can find it

**Comment by ssmusoke** [comment]
@HerbertYiga did you ever test this and see it working

**Comment by HerbertYiga** [comment]
@ssmusoke  i hadn't worked on a fragment for it!!

**Comment by solemabrothers** [comment]
@slubwama here is the PR

**Pull request closed without merging**
